package GUI;

import java.awt.Component;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;

import javax.swing.SwingUtilities;

import json.JsonToJava;
import ca.odell.glazedlists.GlazedLists;
import ca.odell.glazedlists.swing.AutoCompleteSupport;

import com.google.gson.JsonSyntaxException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author apple
 */
public class FirstWindow extends javax.swing.JFrame {

	/**
	 * Creates new form FirstWindow
	 */
	public FirstWindow() {
		initComponents();
		SwingUtilities.invokeLater(doWorkRunnable);
		setSizeAndLocation();
	}
	
	public void setSizeAndLocation() {
		setSize(700, 433);
		
		GUIFunctions.setWindowHeight(this.getHeight());
		GUIFunctions.setWindowWidth(this.getWidth());
		
//		GUIFunctions.setPosX(this.getX());
//		GUIFunctions.setPosX(this.getY());
		
		GUIFunctions.addResizeEvent(this);

	}
	
	public void setSizeAndLocationFromPrev() {
		this.setSize(GUIFunctions.getWindowWidth(), GUIFunctions.getWindowHeight());
		//this.setLocation(GUIFunctions.getPosX(), GUIFunctions.getPosY());
	}

	Runnable doWorkRunnable = new Runnable() {
		@Override
		public void run() {
			GUIFunctions.start();
			Object elements[];
			try {
				elements = JsonToJava.readCategories();
			} catch (JsonSyntaxException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				elements = new Object[] {};
			}
			// jComboBox1.setModel(new JComboBox<>(elements).getModel());
			AutoCompleteSupport.install(jComboBox1,
					GlazedLists.eventListOf(elements));
			jComboBox1.revalidate();
			jComboBox1.repaint();
		}
	};

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jMenu3 = new javax.swing.JMenu();
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jTextFieldLat = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextFieldLong = new javax.swing.JTextField();
		jButtonMap = new javax.swing.JButton();
		jButtonOk = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItemRestart = new javax.swing.JMenuItem();
		jButtonReviews = new javax.swing.JButton();

		jMenu3.setText("jMenu3");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jLabel1.setText("Choose business");

		jComboBox1.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		// jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]
		// { "Item 1", "Item 2", "Item 3", "Item 4" }));
		Object[] elements = new Object[] {};
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		jTextFieldLat.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jTextFieldLat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldLatActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jLabel2.setText("Latitude");

		jLabel3.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jLabel3.setText("Longitude");

		jTextFieldLong.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jTextFieldLong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldLongActionPerformed(evt);
			}
		});

		jButtonMap.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jButtonMap.setText("Select from map");
		jButtonMap.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonMapActionPerformed(evt);
			}
		});

		jButtonOk.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jButtonOk.setText("Topics");
		jButtonOk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonOkActionPerformed(evt);
			}
		});

		jButtonReviews.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jButtonReviews.setText("Reviews");
		jButtonReviews.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonReviewsActionPerformed(evt);
			}
		});

		jMenu1.setText("File");

		jMenuItemRestart.setText("Reset");
		jMenuItemRestart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemRestartActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItemRestart);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(25, 25, 25)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jComboBox1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(149,
																		149,
																		149)
																.addComponent(
																		jButtonOk))
												.addComponent(jLabel1))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jTextFieldLat,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						110,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel2)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGap(43,
																																		43,
																																		43)
																																.addComponent(
																																		jButtonMap)
																																.addGap(84,
																																		84,
																																		84))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGap(103,
																																		103,
																																		103)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						jTextFieldLong,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						110,
																																						javax.swing.GroupLayout.PREFERRED_SIZE)
																																				.addComponent(
																																						jLabel3))
																																.addContainerGap())))))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(50, 50,
																		50)
																.addComponent(
																		jButtonReviews)
																.addGap(0,
																		0,
																		Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(41, 41, 41)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(jLabel2)
												.addComponent(jLabel3))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										48, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jTextFieldLong,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jTextFieldLat,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jComboBox1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(52, 52, 52)
								.addComponent(jButtonMap)
								.addGap(94, 94, 94)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButtonReviews)
												.addComponent(jButtonOk))
								.addGap(41, 41, 41)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void jTextFieldLatActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonMapActionPerformed(java.awt.event.ActionEvent evt) {
		GUIFunctions.showMap();
	}

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {
		GUIFunctions.showWords();
	}

	private void jTextFieldLongActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jMenuItemRestartActionPerformed(java.awt.event.ActionEvent evt) {
		GUIFunctions.resetFirstWindow();
	}

	private void jButtonReviewsActionPerformed(java.awt.event.ActionEvent evt) {
		GUIFunctions.showReviewsFromFirstWindow();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FirstWindow.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FirstWindow.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FirstWindow.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FirstWindow.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				FirstWindow fw = new FirstWindow();
				GUIFunctions.firstWindowFrame = fw;
				fw.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButtonMap;
	private javax.swing.JButton jButtonOk;
	private javax.swing.JButton jButtonReviews;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JTextField jTextFieldLat;
	private javax.swing.JTextField jTextFieldLong;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItemRestart;

	// End of variables declaration
	public javax.swing.JTextField getjTextFieldLat() {
		return jTextFieldLat;
	}

	public void setjTextFieldLat(javax.swing.JTextField jTextFieldLat) {
		this.jTextFieldLat = jTextFieldLat;
	}

	public javax.swing.JTextField getjTextFieldLong() {
		return jTextFieldLong;
	}

	public void setjTextFieldLong(javax.swing.JTextField jTextFieldLong) {
		this.jTextFieldLong = jTextFieldLong;
	}

	public javax.swing.JComboBox getjComboBox1() {
		return jComboBox1;
	}

	public void setjComboBox1(javax.swing.JComboBox jComboBox1) {
		this.jComboBox1 = jComboBox1;
	}
}
